name: Sync and merge upstream repository with your current repository, and create an issue in case of conflict
description: Syncs and merges your current repository with the upstream repository. Inspired in of https://github.com/dabreadman/sync-upstream-repo.
author: fmrico

inputs:
  upstream_repo:
    description: URL of gitHub public upstream repo
    required: true
  upstream_branch:
    description: Branch to merge from upstream (defaults to downstream branch)
    required: false
    default: "main"
  downstream_branch:
    description: Branch to merge into downstream
    required: false
    default: ""
  token:
    description: GitHub Bot token
    required: true
  fetch_args:
    description: Git fetch arguments
    required: false
    default: ""
  merge_args:
    description: Git merge arguments
    required: false
    default: ""
  push_args:
    description: Git push arguments
    required: false
    default: ""
  spawn_logs: 
    description: Toggle to spawn `sync-upstream-repo` with time logs
    required: true
    default: false
outputs:
  merge_result:
    description: Raw result of the git merge command
    value: outputs.merge_result
  conflicts:
    description: List of conflicting files
    value: outputs.conflicts
  completed:
    description: Percentaje of files different with respect upstream
    value: outputs.completed


runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.upstream_repo }}
    - ${{ inputs.upstream_branch }}
    - ${{ inputs.downstream_branch }}
    - ${{ inputs.token }}
    - ${{ inputs.fetch_args }}
    - ${{ inputs.merge_args }}
    - ${{ inputs.push_args }}
    - ${{ inputs.spawn_logs }}

branding:
  icon: "git-merge"
  color: "blue"
